name: Build Haefele Backend

on:
  push: 
    branches: master
  pull_request:
    types: [opened, edited]
    branches: master

env:
  DOTNET_VERSION: '8.1.x'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup .Net Core 8
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Install dependencies
        run: dotnet restore

      - name: Build with .net
        run: dotnet build  --configuration Release --no-restore

      